# SECONDARY COLLIMATOR (4mm)
/gate/ionSource/daughters/name                coll
/gate/ionSource/daughters/insert              cylinder
/gate/coll/placement/setTranslation           0.0 0.0 77.2563 mm
/gate/coll/geometry/setRmax                   10. mm
/gate/coll/geometry/setRmin                   1.3 mm
/gate/coll/geometry/setHeight                 89. mm
/gate/coll/setMaterial                        Tungsten
/gate/coll/vis/setColor                       magenta